### ISSUE TITLE
ImportError of 'tqdm_remote_get' from 'utils' when executing main.py

### ISSUE THREAD

**Issue by Qualot** [columbia-ai-robotics/fit2form#7]
Thank you for sharing the software package!
I cloned the repository yesterday and followed the install sequence on the Ubuntu 20.04 computer, and
executing the command 2.2
```bash
# - generate collision meshes
python main.py --mode collision_mesh
```
returned the following error.

```bash
(fit2form) nakashima@******:******/fit2form$ python main.py --mode collision_mesh
pybullet build time: Oct  8 2020 00:10:46
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from utils import (
ImportError: cannot import name 'tqdm_remote_get' from 'utils' (******/fit2form/utils.py)
(fit2form) nakashima@******:******/fit2form$
```
The tqdm_remote_get function was in another python code common_utils.py,
After fixing main.py like the following diff, the command started without any errors.

```bash
(fit2form) nakashima@******:******/fit2form$ git diff
diff --git a/main.py b/main.py
index 3342ad8..b01d24d 100644
--- a/main.py
+++ b/main.py
@@ -3,10 +3,11 @@ from utils import (
     parse_args,
     setup,
     load_config,
-    tqdm_remote_get,
     setup_train_vae,
     seed_all
 )
+from common_utils import tqdm_remote_get
+
 from tqdm import tqdm
 from environment.meshUtils import (
     create_collision_mesh,
(fit2form) nakashima@******:******/fit2form$
```

Please let me know if I misunderstood anything.
If you feel OK, I might send a PR.

**Comment by submagr** [comment]
Hi @Qualot, Thanks for reporting this issue. You are right. I have made the changes and pushed them. Please pull again and it should work now!

PS: Always happy to receive PRs. Thanks!

**Comment by Qualot** [comment]
@submagr Thank you so much! I would pull and test after finishing 
```$ python main.py --mode grasp_objects```.

OK, I consider sending PRs if I encounter another problem.
